remote_theme: alshedivat/al-folio@master
plugins: 
- jekyll-remote-theme

title: Cap Recognizer
description: An image classification API that classifies 20 different types of caps worn around the world.
author: 
  name: Md. Tasfiq Kamran
  